
from .import views
from django.contrib import admin
from django.urls import path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.hello, name='home'),
    path('services',views.Services, name = 'services'),
    path('rsvp',views.Rsvp, name = 'rsvp'),
    path('process',views.Process, name = 'process'),
    path('wedskey',views.Wedskey, name = 'wedskey'),
    path('contact',views.Contact, name = 'contact'),
    path('collection', views.Collection, name='collection'),
    path('maincategory/<slug:slug>/', views.Category, name='Category'),
    path('maincategory/<slug:sub_category_slug>/<slug:main_category_slug>/', views.main_category_detail, name='maincategory_detail'),
    path('collection/<slug:sub_category_slug>/<slug:main_category_slug>/', views.Collection, name='collection'),
    path('collection-details/<slug:slug>/',views.product_detail, name = 'product_detail'),
    #path('category/<slug:slug>/',views.Category, name = 'Category'),
    path('custom_form',views.custom_form, name = 'custom_form'),
    path("custom_form_save",views.custom_form_save, name='custom_form_save'),
    path("order",views.order, name='order'),
    path('profile',views.profile, name = 'profile'),
    path('profile_edit',views.profile_edit, name = 'profile_edit'),
    path('payment',views.Payment, name = 'payment'),
    path('thank-you',views.Thanks, name = 'thanks'),
    path('login',views.user_login, name = 'login'),
    path('details/', views.details_view, name='details'),
    path('signup',views.signup, name = 'signup'),
    path('logout',views.logout_view, name = 'logout'),
    #path('register', views.Register, name = 'handleregister'),
    path('users/login/', views.CustomLoginView.as_view(), name='login'),
    path('cart/add/<int:id>/', views.cart_add, name='cart_add'),
    path('cart/item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('cart/item_increment/<int:id>/',
         views.item_increment, name='item_increment'),
    path('cart/item_decrement/<int:id>/',
         views.item_decrement, name='item_decrement'),
    path('cart/cart_clear/', views.cart_clear, name='cart_clear'),
    path('cart/cart-detail/',views.cart_detail,name='cart_detail'),
    path('process_order/', views.process_order, name='process_order'),
    path('order_detail/<int:order_id>/', views.order_detail, name='order_detail'),
    path('notification', views.Notification, name='Notification'),
    path('submit_form/', views.submit_form, name='submit_form'),
    path('aboutus/', views.about_us, name='aboutus'),
    path('upload_image/', views.upload_image_view, name='upload_image'),
    path('similar_products/', views.find_similar_products, name='find_similar_products'),
]